version: "2.4"
services:
  app:
    # image: gizmotronic/ccextractor
    build: .
    # command: ["server", "/config.py"]
    #ports: ["127.0.0.1:7465:7465"]
    #tty: true
    privileged: true
    volumes:
      # - "./video-subtitles-ocr.py:/video-subtitles-ocr.py"
      - "./input:/input"
      - "./output:/output"
      - "./cnocr:/root/.cnstd/"
      - "./script:/script"
      
